---
- hosts: all
  vars_files:
    - ../ansible/vars.yml
  become: yes
  tasks:

  - name: Install Recommended Packages
    apt: pkg={{item}} state=present
    with_items:
      - make
      - libcurl4-openssl-dev
      - openssl
      - libssl-dev
      - openssh-client
      - git
      - gdebi-core

  - name: Get repository for build-dep
    shell: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9

  - name: Add repository for build-dep
    shell: add-apt-repository 'deb [arch=amd64,i386] https://cran.rstudio.com/bin/linux/ubuntu xenial/'

  - name: Uncomment source URI cran
    lineinfile:
      dest: /etc/apt/sources.list
      regexp: '^#\s*deb-src [arch=amd64,i386].*$'
      line: 'deb-src [arch=amd64,i386] https://cran.rstudio.com/bin/linux/ubuntu xenial/'

  - name: Update system
    command: apt-get update

  - name: Install Dependencies
    apt: pkg={{item}} state=build-dep
    with_items:
      - r-base

  - name: Build R from Source
    include: ../ansible/buildR-source.yml

  - name: Download Connect DEB
    get_url:
      url: "{{ rsc_download_deb }}"
      dest: "/opt/{{ rsc_deb }}"

  - name: Install Connect
    command: "gdebi -n {{ rsc_deb }}"
    args:
      chdir: /opt

  - name: Update Connect Config File
    lineinfile:
      path: /etc/rstudio-connect/rstudio-connect.gcfg
      line: "NoWarning = true"
      insertafter: 'Listen = :3939'

  - name: Restart Connect Service
    service:
      name: rstudio-connect
      state: restarted

  - name: Wait for RSP Port to Open
    wait_for:
      port: 3939
      delay: 10

  - debug:
      msg: "Access RStudio Connect on Port 3939."
