---
- hosts: all
  vars_files:
    - ../ansible/vars.yml
  become: yes
  tasks:

  - name: Update system
    command: apt-get update

  - name: Install Recommended Packages
    apt: pkg={{item}} state=present
    with_items:
      - make
      - libcurl4-openssl-dev
      - openssl
      - libssl-dev
      - openssh-client
      - git

  - name: Install Dependencies
    apt: pkg={{item}} state=present
    with_items:
      - build-dep
      - r-base
      - gdebi-core

  - name: Build R from Source
    include: ../ansible/buildR-source.yml

  - name: Download Connect DEB
    get_url:
      url: "{{ rsc_download_deb }}"
      dest: "/opt/{{ rsc_rpm }}"

  - name: Install Connect
    command: "gdebi {{ rsc_deb }}"
    args:
      chdir: /opt

  - name: Update Connect Config File
    lineinfile:
      path: /etc/rstudio-connect/rstudio-connect.gcfg
      line: "NoWarning = true"
      insertafter: 'Listen = :3939'

  - name: Restart Connect Service
    service:
      name: rstudio-connect
      state: restarted

  - name: Wait for RSP Port to Open
    wait_for:
      port: 3939
      delay: 10

  - debug:
      msg: "Access RStudio Connect on Port 3939."
