# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.

  config.vm.define "rsp" do |rsp|
    rsp.vm.box = "bento/ubuntu-16.04"
    rsp.vm.network "private_network", ip: "10.0.0.12"
    rsp.vm.hostname = "rstudio-server"
    rsp.vm.provision "ansible" do |ansible|
      ansible.playbook = "rsp-playbook-ubuntu.yml"
    end
  end

  config.vm.define "rsc" do |rsc|
    rsc.vm.box = "bento/ubuntu-16.04"
    rsc.vm.network "private_network", ip: "10.0.0.14"
    rsc.vm.hostname = "rstudio-connect"
    rsc.vm.provision "ansible" do |ansible|
      ansible.playbook = "rsc-playbook-ubuntu.yml"
    end
  end

end
