---
  - name: Install R packages
    command: /opt/R/{{ r_version }}/bin/Rscript -e 'install.packages("{{ item }}", repos = "http://cran.rstudio.com/")'
    with_items:
      - "shiny"
      - "rmarkdown"
      - "tidyverse"
