---
- hosts: all
  become: yes
  tasks:

  - name: Update yum
    command: yum update -y

  - name: Install EPEL
    yum:
      name: epel-release
      state: present

  - name: Install R
    yum:
      name: R
      state: present

  - name: Install Recommended Packages
    yum: pkg={{item}} state=present
    with_items:
      - make
      - gcc
      - gcc-c++
      - libcurl-devel
      - libxml2-devel
      - java-1.7.0-openjdk-devel
      - openssl-devel
      - openssh-clients
      - git

  - name: Download RSP RPM
    get_url:
      url: https://download2.rstudio.org/rstudio-server-rhel-pro-1.1.453-x86_64.rpm
      dest: /opt/rstudio-server-rhel-pro-1.1.453-x86_64.rpm

  - name: Install RSP
    yum:
      name: /opt/rstudio-server-rhel-pro-1.1.453-x86_64.rpm
      state: present
      disable_gpg_check: yes

  - name: Add RStudio User
    user:
      name: rstudio

  - name: Add User Pwd
    shell: echo "rstudio:rstudio" | chpasswd

  - name: Restart RSP Service
    service:
      name: rstudio-server
      state: restarted

  - name: Wait for RSP Port to Open
    wait_for:
      port: 8787
      delay: 10

  - debug:
      msg: "Access RStudio Server Pro on Port 8787."
