---
- hosts: all
  vars_files:
    - ../ansible/vars.yml
    - ./centos-vars.yml
  become: yes
  tasks:

  - name: Stand Up Server Server
    include: ./r-server-playbook-centos.yml

  - name: Download RSP RPM
    get_url:
      url: "{{ rsp_download_rpm }}"
      dest: "/opt/{{ rsp_rpm }}"

  - name: Install RSP
    yum:
      name: "/opt/{{ rsp_rpm }}"
      state: present
      disable_gpg_check: yes

  - name: Configure RSP
    include: ../ansible/rsp-setup.yml


