---
- hosts: all
  vars_files:
    - ../ansible/vars.yml
  become: yes
  tasks:

  - name: Update yum
    command: yum update -y

  - name: Install ntp
    yum:
      name: ntp
      state: present

  - name: Enable ntpd service
    service:
      name: ntpd
      state: started
      enabled: yes

  - name: Install EPEL
    yum:
      name: epel-release
      state: present

  - name: Install Recommended Packages
    yum: pkg={{item}} state=present
    with_items:
      - make
      - gcc
      - gcc-c++
      - libcurl-devel
      - libxml2-devel
      - java-1.7.0-openjdk-devel
      - openssl-devel
      - openssh-clients
      - git

  - name: Install R Dependencies
    command: yum-builddep R -y

  - name: Build R from Source
    include: ../ansible/buildR-source.yml

  - name: Download RSPM RPM
    get_url:
      url: "{{ rspm_download_rpm }}"
      dest: "/opt/{{ rspm_rpm }}"

  - name: Install RSPM
    yum:
      name: "/opt/{{ rspm_rpm }}"
      state: present
      disable_gpg_check: yes

  - name: Add RStudio User
    user:
      name: rstudio

  - name: Add User Pwd
    shell: echo "rstudio:rstudio" | chpasswd

  - name: Add User to RSPM Group
    shell: usermod -aG rstudio-pm rstudio

  - name: Restart RSPM Service
    service:
      name: rstudio-pm
      state: restarted

  - name: Wait for RSPM Port to Open
    wait_for:
      port: 4242
      delay: 10

  - debug:
      msg: "Access RStudio Package Manager on Port 4242."
