---
- hosts: all
  vars_files:
    - ../ansible/vars.yml
    - ./centos-vars.yml
  become: yes
  tasks:

  - name: Stand up Server
    include: ./r-server-playbook-centos.yml

  - name: Download RSPM RPM
    get_url:
      url: "{{ rspm_download_rpm }}"
      dest: "/opt/{{ rspm_rpm }}"

  - name: Install RSPM
    yum:
      name: "/opt/{{ rspm_rpm }}"
      state: present
      disable_gpg_check: yes

  - name: Setup RSPM
    include: ../ansible/rspm_setup.yml